# Site settings
title: DG's Blog
SEOTitle: Python Club
header-img: img/home-bg.jpg
email: DGmzg@gmail.com
description: "曾经跨马游春山，归来已不再少年"
keyword: "Python, python, python club, DG, DGmzg, 大刚, 大刚的博客, DG Blog, DG's Blog, 编程, web, 前端, 后端"
url: "http://pythonclub.club"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     u/5381696112
zhihu_username:     ma-zhi-gang-24
github_username:    DGmzg
facebook_username:  ?q=马志刚(david maa)



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  

# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "伪文青，半吊子程序员<br>人生苦短，我学python"
sidebar-avatar: /img/IMG-DG.JPG      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
        title: "I",
        href: "#"
    },{
        title: "LOVE",
        href: "#"
    },{
        title: "YOU",
        href: "#"
    },{
        title: "SO",
        href: "#"
    },{
        title: "MUCH",
        href: "#"
    }
]
